// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ytfasdmvmovlfyyjluej.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inl0ZmFzZG12bW92bGZ5eWpsdWVqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQwNjIzNTQsImV4cCI6MjA2OTYzODM1NH0.xDt-ytHfGCuO1SRjne4uK4ly7DqIHpEflTaTPVnST5s";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});